#!/usr/bin/env python3
"""
Display all the visualizations generated by the Dartboard pipeline (v2).
"""

import os
import textwrap

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

from pipeline.config import VIZ_DIR, ensure_directories


def _build_visualization_manifest():
    """Ordered list of expected visualizations."""
    return [
        ("NY Load Nodes", "ny_load_nodes.png", "Load nodes created from Census ZCTA data for New York"),
        ("TX Load Nodes", "tx_load_nodes.png", "Load nodes created from Census ZCTA data for Texas"),
        ("Substations", "substations.png", "Clustered substations for both NY and TX"),
        ("Transmission Backbone", "backbone.png", "Pruned transmission line topology"),
        ("Voltage Maps", "voltage_maps.png", "Final grids with 115kV and 345kV voltage assignments"),
    ]


def show_visualizations_v2():
    """Display all pipeline visualizations with a clean, adaptive layout."""
    ensure_directories()

    visualizations = _build_visualization_manifest()
    existing = []
    missing = []

    for title, filename, description in visualizations:
        filepath = os.path.join(VIZ_DIR, filename)
        if os.path.exists(filepath):
            existing.append((title, filepath, description))
        else:
            missing.append((title, filename, description))

    if not existing:
        print("No visualization images found. Run the pipeline to generate them first.")
        print(f"Expected directory: {VIZ_DIR}")
        return

    rows = len(existing)
    fig_height = max(4, 3.8 * rows)
    fig, axes = plt.subplots(
        nrows=rows,
        ncols=1,
        figsize=(16, fig_height),
        constrained_layout=True,
    )

    if rows == 1:
        axes = [axes]

    fig.suptitle(
        "Dartboard Pipeline Visualizations",
        fontsize=18,
        fontweight="bold",
    )
    fig.patch.set_facecolor("#f7f6f2")

    for ax, (title, filepath, description) in zip(axes, existing):
        img = mpimg.imread(filepath)
        ax.imshow(img)
        wrapped = textwrap.fill(description, width=70)
        ax.set_title(f"{title}\n{wrapped}", fontsize=12, pad=10)
        ax.axis("off")

    summary_path = os.path.join(VIZ_DIR, "pipeline_summary_v2.png")
    plt.savefig(summary_path, dpi=200, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.show()

    print("\n" + "=" * 60)
    print("DARTBOARD PIPELINE VISUALIZATION SUMMARY (V2)")
    print("=" * 60)
    print(f"Generated visualizations saved in: {VIZ_DIR}")
    print(f"Summary image saved as: {summary_path}")
    print("\nPhase-by-phase results:")
    for title, filename, description in visualizations:
        filepath = os.path.join(VIZ_DIR, filename)
        if os.path.exists(filepath):
            print(f"✓ {title}: {description}")
        else:
            print(f"✗ {title}: File not found ({filename})")
    print("=" * 60)


if __name__ == "__main__":
    show_visualizations_v2()
