#!/usr/bin/env python3
"""
Display all the visualizations generated by the Dartboard pipeline.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
from pipeline.config import VIZ_DIR

def show_visualizations():
    """Display all pipeline visualizations."""
    
    # List of visualizations in the order they're created
    visualizations = [
        ("NY Load Nodes", "ny_load_nodes.png", "Load nodes created from Census ZCTA data for New York"),
        ("TX Load Nodes", "tx_load_nodes.png", "Load nodes created from Census ZCTA data for Texas"), 
        ("Substations", "substations.png", "Clustered substations for both NY and TX"),
        ("Transmission Backbone", "backbone.png", "Pruned transmission line topology"),
        ("Voltage Maps", "voltage_maps.png", "Final grids with 115kV and 345kV voltage assignments")
    ]
    
    # Set up the figure with subplots
    fig = plt.figure(figsize=(20, 25))
    
    for i, (title, filename, description) in enumerate(visualizations):
        filepath = os.path.join(VIZ_DIR, filename)
        
        if os.path.exists(filepath):
            ax = fig.add_subplot(5, 1, i+1)
            
            # Load and display image
            img = mpimg.imread(filepath)
            ax.imshow(img)
            ax.set_title(f"{title}\n{description}", fontsize=14, pad=10)
            ax.axis('off')
        else:
            print(f"Warning: {filename} not found")
    
    plt.tight_layout()
    plt.savefig(os.path.join(VIZ_DIR, "pipeline_summary.png"), 
                dpi=200, bbox_inches='tight')
    plt.show()
    
    print("\n" + "="*60)
    print("DARTBOARD PIPELINE VISUALIZATION SUMMARY")
    print("="*60)
    print(f"Generated visualizations saved in: {VIZ_DIR}")
    print("\nPhase-by-phase results:")
    for title, filename, description in visualizations:
        filepath = os.path.join(VIZ_DIR, filename)
        if os.path.exists(filepath):
            print(f"✓ {title}: {description}")
        else:
            print(f"✗ {title}: File not found")
    print("="*60)

if __name__ == "__main__":
    show_visualizations()